baseURL: 'https://blog.chaimi.cc/'
languageCode: 'zh-cn'
title: '柴米の拾光'
theme: 'hugo-PaperMod'
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

params:
  author: chaimi
  DateFormat: "2006 01 02"
  ShowCodeCopyButtons: true
  # showtoc: true

  homeInfoParams:
    Title: なにこれ！？
    Content: ただ記録だけ。あなたに、私も...

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon.ico"
    favicon32x32: "/favicon.ico"
    apple_touch_icon: "/favicon.ico"
    safari_pinned_tab: "/favicon.ico"

menu:
  main:
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 10
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai

  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - '$$'
            - '$$'
          inline:
          - - '$'
            - '$'