baseURL: https://blog.chaimi.cc/
languageCode: zh
defaultContentLanguage: zh
title: 柴米の拾光
theme: hugo-PaperMod
enableRobotsTXT: true
enableInlineShortcodes: true

minify:
  disableXML: true
  minifyOutput: true

params:
  author: chaimi
  description: "柴米的个人博客"
  DateFormat: "2006 01 02"
  ShowCodeCopyButtons: true
  defaultTheme: dark # auto, light
  disableScrollToTop: true

  homeInfoParams:
    Title: なにこれ！？
    Content: ただ記録だけ。あなたに、私も...

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "icon.webp"
    # favicon16x16: "/favicon.ico"
    # favicon32x32: "/favicon.ico"
    apple_touch_icon: "icon.webp"
    safari_pinned_tab: "icon.webp"

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    style: github-dark

  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - '$$'
            - '$$'
          inline:
          - - '$'
            - '$'